/*
 * Compiler version header generated by PawnMC's CMake build.
 * File: version.h
 * Location: app/src/main/cpp
 * License: Apache License (v2)
 *
 * The Pawn submodules each ship a `compiler/version.h.in` that CMake normally configures
 * into the build tree. That template is only present in a full checkout of
 * pawn-lang/compiler with its own `build` helper; PawnMC builds the `compiler/` sources
 * directly, so the two constants the compiler needs are supplied from here instead.
 *
 * `VERSION_INT` is the packed form (`major << 8 | minor`) that `sc1.c` prints in the
 * banner and compares against. `VERSION_STR` is what ends up in that banner, in the
 * `-v` report, and in the AMX header's compiler-version field.
 *
 * VERSION_BUILD, VERSION_STR and VERSION_INT are redefined per target by CMakeLists.txt
 * (`-DVERSION_STR=...` etc. on the command line where it already passes them); this file
 * only provides the baseline that keeps a bare `clang` invocation compiling.
 */

# ifndef PAWN_VERSION_H
# define PAWN_VERSION_H

# ifndef VERSION_MAJOR
# define VERSION_MAJOR 3
# endif

# ifndef VERSION_MINOR
# define VERSION_MINOR 10
# endif

# ifndef VERSION_BUILD
# define VERSION_BUILD 11
# endif

# ifndef VERSION_INT
# define VERSION_INT ((VERSION_MAJOR << 8) | VERSION_MINOR)
# endif

# ifndef VERSION_STR
# define VERSION_STR "3.10.11"
# endif

# define PAWNMC_BUILD 1

# endif // PAWN_VERSION_H
