package com.rvdjv.pawnmc.ui.theme

import androidx.compose.ui.graphics.Color

// Dark 
val md_theme_dark_onPrimary = Color(0xFF13111C)
val md_theme_dark_primaryContainer = Color(0xFF4C3B82)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9E6F2)
val md_theme_dark_secondary = Color(0xFF8B8699)
val md_theme_dark_onSecondary = Color(0xFF13111C)
val md_theme_dark_secondaryContainer = Color(0xFF2A2636)
val md_theme_dark_onSecondaryContainer = Color(0xFFE9E6F2)
val md_theme_dark_tertiary = Color(0xFFC4B5FD)
val md_theme_dark_onTertiary = Color(0xFF13111C)
val md_theme_dark_tertiaryContainer = Color(0xFF3A2F52)
val md_theme_dark_onTertiaryContainer = Color(0xFFE9E6F2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF13111C)
val md_theme_dark_onBackground = Color(0xFFE9E6F2)
val md_theme_dark_surface = Color(0xFF1C1829)
val md_theme_dark_onSurface = Color(0xFFE9E6F2)
val md_theme_dark_surfaceVariant = Color(0xFF251F35)
val md_theme_dark_onSurfaceVariant = Color(0xFF8B8699)
val md_theme_dark_outline = Color(0xFF8B8699)
val md_theme_dark_outlineVariant = Color(0xFF3A3450)

val status_success = Color(0xFF4ADE80)
val status_success_container = Color(0xFF1E3A2C)
val status_error = Color(0xFFF87171)
val status_error_container = Color(0xFF3F1D24)
val status_idle = Color(0xFF8B8699)

//light
val md_theme_light_primary = Color(0xFF6D4DB8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE9DDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF250F52)
val md_theme_light_secondary = Color(0xFF5F5A6B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE7E0F0)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1829)
val md_theme_light_tertiary = Color(0xFF7C5DC7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBE0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF271A45)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBF8FF)
val md_theme_light_onBackground = Color(0xFF1C1829)
val md_theme_light_surface = Color(0xFFFBF8FF)
val md_theme_light_onSurface = Color(0xFF1C1829)
val md_theme_light_surfaceVariant = Color(0xFFE6E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF5F5A6B)
val md_theme_light_outline = Color(0xFF7C7689)
val md_theme_light_outlineVariant = Color(0xFFCBC4D6)