package com.rvdjv.pawnmc.ui.theme

import androidx.compose.ui.graphics.Color

// Dark 
val md_theme_dark_primary = Color(0xFFCFBCFF)
val md_theme_dark_onPrimary = Color(0xFF13111C)
val md_theme_dark_primaryContainer = Color(0xFF4C3B82)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9E6F2)
val md_theme_dark_secondary = Color(0xFF8B8699)
val md_theme_dark_onSecondary = Color(0xFF13111C)
val md_theme_dark_secondaryContainer = Color(0xFF2A2636)
val md_theme_dark_onSecondaryContainer = Color(0xFFE9E6F2)
val md_theme_dark_tertiary = Color(0xFFC4B5FD)
val md_theme_dark_onTertiary = Color(0xFF13111C)
val md_theme_dark_tertiaryContainer = Color(0xFF3A2F52)
val md_theme_dark_onTertiaryContainer = Color(0xFFE9E6F2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF13111C)
val md_theme_dark_onBackground = Color(0xFFE9E6F2)
val md_theme_dark_surface = Color(0xFF1C1829)
val md_theme_dark_onSurface = Color(0xFFE9E6F2)
val md_theme_dark_surfaceVariant = Color(0xFF251F35)
val md_theme_dark_onSurfaceVariant = Color(0xFF8B8699)
val md_theme_dark_outline = Color(0xFF8B8699)
val md_theme_dark_outlineVariant = Color(0xFF3A3450)
// Explicit surface elevation roles so every area keeps a visible depth step,
// mirroring the tonal ramp used by the light scheme.
val md_theme_dark_surfaceDim = Color(0xFF13111C)
val md_theme_dark_surfaceBright = Color(0xFF3B3547)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0E0B16)
val md_theme_dark_surfaceContainerLow = Color(0xFF1C1829)
val md_theme_dark_surfaceContainer = Color(0xFF211C2E)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2B2639)
val md_theme_dark_surfaceContainerHighest = Color(0xFF363046)
val md_theme_dark_surfaceTint = Color(0xFFCFBCFF)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE9E6F2)
val md_theme_dark_inverseOnSurface = Color(0xFF322C3F)
val md_theme_dark_inversePrimary = Color(0xFF6D4DB8)

val status_success = Color(0xFF4ADE80)
val status_success_container = Color(0xFF1E3A2C)
val status_error = Color(0xFFF87171)
val status_error_container = Color(0xFF3F1D24)
val status_idle = Color(0xFF8B8699)

//light
val md_theme_light_primary = Color(0xFF6D4DB8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE9DDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF250F52)
val md_theme_light_secondary = Color(0xFF5F5A6B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE7E0F0)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1829)
val md_theme_light_tertiary = Color(0xFF7C5DC7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBE0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF271A45)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
// The light scheme used to be flat (background == surface, almost-white surfaceVariant),
// which made cards, toolbars, tonal buttons and the editor blend into one bright mass.
// It now follows a real elevation ramp: the page is slightly tinted, surfaces are
// brighter, and containers step down in tone from Lowest to Highest.
val md_theme_light_background = Color(0xFFF3EDF7)
val md_theme_light_onBackground = Color(0xFF1C1829)
val md_theme_light_surface = Color(0xFFFBF8FF)
val md_theme_light_onSurface = Color(0xFF1C1829)
val md_theme_light_surfaceVariant = Color(0xFFE4DDEA)
val md_theme_light_onSurfaceVariant = Color(0xFF575163)
val md_theme_light_outline = Color(0xFF7A7488)
val md_theme_light_outlineVariant = Color(0xFFCDC6D6)
val md_theme_light_surfaceDim = Color(0xFFDCD5E1)
val md_theme_light_surfaceBright = Color(0xFFFBF8FF)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFFBF8FF)
val md_theme_light_surfaceContainer = Color(0xFFF6F1F9)
val md_theme_light_surfaceContainerHigh = Color(0xFFF1EBF4)
val md_theme_light_surfaceContainerHighest = Color(0xFFEAE3EF)
val md_theme_light_surfaceTint = Color(0xFF6D4DB8)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF322C3F)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF8)
val md_theme_light_inversePrimary = Color(0xFFCFBCFF)